/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface KizunaAvatar {
        "appearance": string;
        "image": string;
        "indicator": boolean;
        "rounded": string;
        "size": string | number;
        "status": string;
        "toolkit": string;
    }
}
declare global {
    interface HTMLKizunaAvatarElement extends Components.KizunaAvatar, HTMLStencilElement {
    }
    var HTMLKizunaAvatarElement: {
        prototype: HTMLKizunaAvatarElement;
        new (): HTMLKizunaAvatarElement;
    };
    interface HTMLElementTagNameMap {
        "kizuna-avatar": HTMLKizunaAvatarElement;
    }
}
declare namespace LocalJSX {
    interface KizunaAvatar {
        "appearance"?: string;
        "image"?: string;
        "indicator"?: boolean;
        "rounded"?: string;
        "size"?: string | number;
        "status"?: string;
        "toolkit"?: string;
    }
    interface IntrinsicElements {
        "kizuna-avatar": KizunaAvatar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "kizuna-avatar": LocalJSX.KizunaAvatar & JSXBase.HTMLAttributes<HTMLKizunaAvatarElement>;
        }
    }
}
