/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface KizunaAvatar {
        "appearance": string;
        "image": string;
        "indicator": boolean;
        "rounded": string;
        "size": string | number;
        "status": string;
        "toolkit": string;
    }
    interface KizunaButton {
        "disabled": boolean;
        "handleOnClick": Function;
        "icon": string;
        "text": string;
        "type": string;
    }
    interface KizunaToggle {
        "checked": boolean;
        "disabled": boolean;
    }
}
declare global {
    interface HTMLKizunaAvatarElement extends Components.KizunaAvatar, HTMLStencilElement {
    }
    var HTMLKizunaAvatarElement: {
        prototype: HTMLKizunaAvatarElement;
        new (): HTMLKizunaAvatarElement;
    };
    interface HTMLKizunaButtonElement extends Components.KizunaButton, HTMLStencilElement {
    }
    var HTMLKizunaButtonElement: {
        prototype: HTMLKizunaButtonElement;
        new (): HTMLKizunaButtonElement;
    };
    interface HTMLKizunaToggleElement extends Components.KizunaToggle, HTMLStencilElement {
    }
    var HTMLKizunaToggleElement: {
        prototype: HTMLKizunaToggleElement;
        new (): HTMLKizunaToggleElement;
    };
    interface HTMLElementTagNameMap {
        "kizuna-avatar": HTMLKizunaAvatarElement;
        "kizuna-button": HTMLKizunaButtonElement;
        "kizuna-toggle": HTMLKizunaToggleElement;
    }
}
declare namespace LocalJSX {
    interface KizunaAvatar {
        "appearance"?: string;
        "image"?: string;
        "indicator"?: boolean;
        "rounded"?: string;
        "size"?: string | number;
        "status"?: string;
        "toolkit"?: string;
    }
    interface KizunaButton {
        "disabled"?: boolean;
        "handleOnClick"?: Function;
        "icon"?: string;
        "text"?: string;
        "type"?: string;
    }
    interface KizunaToggle {
        "checked"?: boolean;
        "disabled"?: boolean;
    }
    interface IntrinsicElements {
        "kizuna-avatar": KizunaAvatar;
        "kizuna-button": KizunaButton;
        "kizuna-toggle": KizunaToggle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "kizuna-avatar": LocalJSX.KizunaAvatar & JSXBase.HTMLAttributes<HTMLKizunaAvatarElement>;
            "kizuna-button": LocalJSX.KizunaButton & JSXBase.HTMLAttributes<HTMLKizunaButtonElement>;
            "kizuna-toggle": LocalJSX.KizunaToggle & JSXBase.HTMLAttributes<HTMLKizunaToggleElement>;
        }
    }
}
